In [2]:
import pandas as pd
df = pd.read_csv('/content/index_1.csv')

In [3]:
df.head(10)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,Americano with Milk

In [4]:
df.tail(10)

,date,datetime,cash_type,card,money,coffee_name
3626,2025-03-22,2025-03-22 15:57:58.183,card,ANON-0000-0000-1302,21.06,Espresso
3627,2025-03-22,2025-03-22 16:26:59.766,card,ANON-0000-0000-1274,35.76,Latte
3628,2025-03-22,2025-03-22 17:53:35.942,card,ANON-0000-0000-1274,30.86,Americano with Milk
3629,2025-03-22,2025-03-22 19:16:52.727,card,ANON-0000-0000-1314,30.86,Americano with Milk
3630,2025-03-23,2025-03-23 10:07:11.278,card,ANON-0000-0000-1196,35.76,Latte
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [5]:
df.shape

(3636, 6)

In [6]:
df.columns

Index(['date', 'datetime', 'cash_type', 'card', 'money', 'coffee_name'], dtype='object')

In [7]:
df.dtypes

date            object
datetime        object
cash_type       object
card            object
money          float64
coffee_name     object
dtype: object

In [8]:
df.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df['coffee_name'].unique()

array(['Latte', 'Hot Chocolate', 'Americano', 'Americano with Milk',
       'Cocoa', 'Cortado', 'Espresso', 'Cappuccino'], dtype=object)

In [11]:
sold = df['coffee_name'].value_counts()
sold

coffee_name
Americano with Milk    824
Latte                  782
Americano              578
Cappuccino             501
Cortado                292
Hot Chocolate          282
Cocoa                  243
Espresso               134
Name: count, dtype: int64

In [12]:
sold.idxmax()

'Americano with Milk'

In [13]:
sold.idxmin()

'Espresso'

In [14]:
df['money'].sum()

np.float64(115431.58)

In [15]:
df['money'].mean()

np.float64(31.74685918591859)

In [16]:
df['money'].min()

18.12

In [17]:
df['money'].max()

40.0

In [18]:
df['money'].std()

4.919925803555333

In [19]:
df[df['money']> 35]

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.70,Hot Chocolate
...,...,...,...,...,...,...
3630,2025-03-23,2025-03-23 10:07:11.278,card,ANON-0000-0000-1196,35.76,Latte
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [20]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [21]:
df['month'] = df['datetime'].dt.month
df['hour'] = df['datetime'].dt.hour

In [22]:
df.groupby(['month','coffee_name'])['money'].sum()

month  coffee_name
1      Americano               649.00
       Americano with Milk    1604.72
       Cappuccino              965.52
       Cocoa                   500.64
       Cortado                 571.12
                               ...
12     Cocoa                   750.96
       Cortado                 804.76
       Espresso                252.72
       Hot Chocolate           929.76
       Latte                  1680.72
Name: money, Length: 96, dtype: float64

In [23]:
df['hour'].value_counts().idxmax()

np.int32(10)

In [24]:
df.groupby('month')['money'].sum().idxmax()

np.int32(3)